# Generated by Django 3.2.3 on 2021-05-17 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('eventdate', models.DateField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=200, verbose_name='Event Happening At')),
                ('lastdatetoreg', models.DateField(verbose_name='Registration Deadline')),
                ('maxparticipants', models.PositiveIntegerField(verbose_name='Max. Participants')),
                ('createduserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.TextField()),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeverMissIt.eventdetails')),
                ('teamleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
